# Test Connection at SQL Server 2000
development:
  adapter: sqlserver
  database: KpiManagement
  host: SUNQI
  username: root
  password: root

test:
  adapter: sqlserver
  database: KpiManagement
  host: SUNQI
  username: root
  password: root

production:
  adapter: sqlserver
  database: KpiManagement
  host: SUNQI
  username: root
  password: root